name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Build Packages
        run: yarn build

      - name: Deploy Changes
        run: yarn deploy
        env:
          OARE_DB_URL: ${{ secrets.OARE_DB_URL }}
        if: github.ref == 'refs/heads/main'
